cabledb/src/main/java/org/openepics/cable/ui/LoginController.java
/*
 * Copyright (c) 2014 European Spallation Source
 * Copyright (c) 2014 Cosylab d.d.
 *
 * This file is part of Cable Database.
 * Cable Database is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 2 of the License, or any newer version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see https://www.gnu.org/licenses/gpl-2.0.txt
 */
package org.openepics.cable.ui;

import java.io.IOException;
import java.io.Serializable;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.application.FacesMessage.Severity;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

import org.openepics.cable.CableProperties;
import org.openepics.cable.services.SessionService;

import se.esss.ics.rbac.loginmodules.service.Message;

/**
 * A UI controller bean for the login / logout button and form.
 *
 * @author <a href="mailto:sunil.sah@cosylab.com">Sunil Sah</a>
 */
@ManagedBean
@ViewScoped
public class LoginController implements Serializable {

    private static final long serialVersionUID = 5984791196886929176L;

    private static final Logger LOGGER = Logger.getLogger(LoginController.class.getName());

    @Inject
    private SessionService sessionService;

    private String inputUsername;
    private String inputPassword;

    private boolean loginRequested;

    private void clearPassword() {
        inputPassword = null;
    }

    /** Initializes the bean for initial view display. */
    @PostConstruct
    public void init() {
        loginRequested = !sessionService.isLoggedIn();
    }

    /** Requests login. */
    public void requestLogin() {
        LOGGER.fine("Invoked request login.");
        loginRequested = true;
    }

    /** Performs login. */
    public void login() {
        LOGGER.fine("Invoked login.");
        try {
            final Message result = sessionService.login(inputUsername, inputPassword);
            if (result.isSuccessful())
                loginRequested = false;

            showMessage(result, "Sign In");
        } finally {
            clearPassword();
        }
    }

    /** Performs logout. */
    public void logout() {
        LOGGER.fine("Invoked logout.");
        try {
            final Message result = sessionService.logout();
            showMessage(result, "Sign Out");
        } finally {
            clearPassword();
        }
        loginRequested = true;
        try {
            FacesContext.getCurrentInstance().getExternalContext()
                    .redirect(CableProperties.getInstance().getApplicationBaseURL()
                            + FacesContext.getCurrentInstance().getViewRoot().getViewId());
        } catch (IOException e) {
            e.printStackTrace();
        }
        return;
    }

    /** Cancels login in progress. */
    public void cancel() {
        LOGGER.fine("Invoked cancel.");
        clearPassword();
        loginRequested = false;
    }

    /** @return the inputUsername */
    public String getInputUsername() {
        return inputUsername;
    }

    /**
     * @param inputUsername
     *            the inputUsername to set
     */
    public void setInputUsername(String inputUsername) {
        this.inputUsername = inputUsername;
    }

    /** @return the inputPassword */
    public String getInputPassword() {
        return inputPassword;
    }

    /**
     * @param inputPassword
     *            the inputPassword to set
     */
    public void setInputPassword(String inputPassword) {
        this.inputPassword = inputPassword;
    }

    /** @return the true if the login is currently requested, else false */
    public boolean isLoginRequested() {
        return loginRequested;
    }

    /** @return the true, if the login will be redirected to cable page */
    public boolean isCablesPage() {
        return FacesContext.getCurrentInstance().getViewRoot().getViewId().equals("/cables.xhtml");
    }

    private void showMessage(Message result, String action) {

        final Severity severity = result.isSuccessful() ? FacesMessage.SEVERITY_INFO : FacesMessage.SEVERITY_ERROR;
        final String summary = action + " " + (result.isSuccessful() ? "Succeeded" : "Failed");
        final String message = result.getMessage();

        final FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage(severity, summary, message));
    }
}

cabledb/src/main/webapp/WEB-INF/cableTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
  xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:p="http://primefaces.org/ui"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:h="http://java.sun.com/jsf/html">

<h:head>
  <f:facet name="first">
    <meta http-equiv="X-UA-Compatible" content="IE=EDGE" />
  </f:facet>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <link href="resources/css/webfontkit/stylesheet.css" rel="stylesheet"
    type="text/css" />
  <link href="resources/css/default.css" rel="stylesheet"
    type="text/css" />
  <link href="resources/css/cssLayout.css" rel="stylesheet"
    type="text/css" />
  <title>#{msgs.title}</title>
  <h:outputScript library="js" name="cabledb-common.js" />
  <ui:insert name="head_content" />
</h:head>

<h:body>

  <p:dialog modal="true" widgetVar="statusDialog" showHeader="false"
    draggable="false" closable="false" resizable="false">
    <p:graphicImage value="/resources/images/ajax-loader.gif" />
  </p:dialog>

  <p:outputPanel id="full" layout="block">
    <div id="menu" style="padding: 10px 15px 0px 15px">
      <ui:include src="/WEB-INF/includes/menubar.xhtml" />
    </div>

    <div style="padding: 15px 15px 0px 15px">
      <p:growl id="cableDBGrowl" showDetail="true" />
      <ui:insert name="content">Content</ui:insert>
    </div>

    <div class="footer-message">
      <h:outputText value="#{msgs.title} v#{msgs.titleVersion} - " />
      <a style="color: #A8A8A8;"
        href="mailto:#{msgs.supportEmail}?subject=#{msgs.supportEmailSubject}">Contact
        us</a>
    </div>
  </p:outputPanel>

  <h:form id="loginForm">
    <p:dialog id="loginDialog" widgetVar="loginDialog" modal="true"
      visible="#{loginController.loginRequested}" closable="false">

      <f:facet name="header">
        <h:outputText value="Sign In" />
      </f:facet>
      <p:panelGrid id="grid" columns="2" styleClass="borderless">
        <h:outputLabel for="username" value="Username" />
        <h:panelGroup>
          <p:inputText id="username"
            value="#{loginController.inputUsername}" label="Username" />
          <p:watermark for="username" value="Enter username" />
          <p:message for="username" />
        </h:panelGroup>
        <h:outputLabel for="passwd" value="Password" />
        <h:panelGroup>
          <p:password id="passwd"
            value="#{loginController.inputPassword}" label="Password" />
          <p:watermark for="passwd" value="Enter password" />
          <p:message for="passwd" />
        </h:panelGroup>
      </p:panelGrid>
      <p:separator />

      <p:commandButton value="Sign In" update=":full :loginForm"
        action="#{loginController.login()}" style="float: left"
        onstart="start()" oncomplete="stop(); remoteCommandLoad();"
        rendered="#{loginController.cablesPage}" />

      <p:commandButton value="Sign In" update=":full :loginForm"
        action="#{loginController.login()}" style="float: left"
        onstart="start()" oncomplete="stop()"
        rendered="#{!loginController.cablesPage}" />

    </p:dialog>
  </h:form>

  <p:dialog modal="true" id="popupDialog" header="Warning"
    widgetVar="popupDialog"
    visible="#{applicationStateManager.namesServiceWarning}"
    closable="true">
    <div>The connection to the Naming Service could not be
      established.</div>
    <p:spacer width="32" />
    <p:commandButton value="Close" title="Close dialog."
      style="float:right" onclick="PF('popupDialog').hide();"
      icon="ui-icon-close" />
  </p:dialog>

  <script type="text/javascript">
            jQuery(window).resize(function() {
                adjustFooterPosition();
            });

            jQuery(document).ready(function() {
                adjustFooterPosition();
            });
        </script>

  <ui:include src="/resources/dialogs/error.xhtml" />
</h:body>

</html>

cabledb/src/main/webapp/WEB-INF/historyDataTable.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:p="http://primefaces.org/ui"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:h="http://java.sun.com/jsf/html">
  <div style="width: calc(100% - 1em)">
    <p:dataTable id="historyTable" var="history"
      value="#{controller.lazyModel}" rowKey="#{history.id}"
      widgetVar="historyTable" class="dialogListTable"
      emptyMessage="No records found." scrollable="true"
      liveScroll="true" scrollWidth="100%" scrollHeight="#{tableHeight}"
      scrollRows="150" rows = "150" lazy="true">

      <p:ajax event="filter" update="#{updateOnFilter}" />

      <p:column id="timestampColumn" sortBy="#{history.timestamp}"
        style="width:15%; min-width:100px"
        filterStyle="width:15%; min-width:100px"
        filterBy="#{history.timestamp}" filterMatchMode="contains">
        <f:facet name="header">
          <h:outputText value="Timestamp"
            title="History entry timestamp." />
        </f:facet>
        <h:outputText value="#{history.timestamp}" />
      </p:column>

      <p:column id="userColumn" sortBy="#{history.userId}"
        style="width:10%; min-width:100px"
        filterStyle="width:10%; min-width:100px"
        filterBy="#{history.userId}" filterMatchMode="contains">
        <f:facet name="header">
          <h:outputText value="User" title="User." />
        </f:facet>
        <h:outputText value="#{history.user}" />
      </p:column>

      <p:column id="entityType" sortBy="#{history.entityType}"
        style="width:10%; min-width:60px"
        filterStyle="width:10%; min-width:60px"
        filterBy="#{history.entityType}" filterMatchMode="exact"
        filterOptions="#{historyRequestManager.entityTypeValues}"
        rendered="#{showType}">
        <f:facet name="header">
          <h:outputText value="Entity Type" title="Entity Type." />
        </f:facet>
        <h:outputText value="#{history.entityType}" />
      </p:column>

      <p:column id="operationColumn" sortBy="#{history.operation}"
        style="width:10%; min-width:60px"
        filterStyle="width:10%; min-width:60px"
        filterBy="#{history.operation}" filterMatchMode="exact"
        filterOptions="#{historyRequestManager.operationValues}">
        <f:facet name="header">
          <h:outputText value="Operation" title="Operation." />
        </f:facet>
        <h:outputText value="#{history.operation}" />
      </p:column>

      <p:column id="entityNameColumn" sortBy="#{history.entityName}"
        style="width:20%; min-width:100px"
        filterStyle="width:20%; min-width:100px"
        filterBy="#{history.entityName}" filterMatchMode="contains">
        <f:facet name="header">
          <h:outputText value="Entity Name" title="Entity name." />
        </f:facet>
        <h:outputText value="#{history.entityName}" />
      </p:column>

      <p:column id="entityIdColumn" sortBy="#{history.entityId}"
        style="width:10%; min-width:60px"
        filterStyle="width:10%; min-width:60px"
        filterBy="#{history.entityId}" filterMatchMode="contains">
        <f:facet name="header">
          <h:outputText value="Entity ID" title="Entity ID." />
        </f:facet>
        <h:outputText value="#{history.entityId}" />
      </p:column>

      <p:column id="entryColumn" sortBy="#{history.entry}"
        style="width:25%; min-width:150"
        filterStyle="width:25%; min-width:150px"
        filterBy="#{history.entry}" filterMatchMode="contains">
        <f:facet name="header">
          <h:outputText value="Change" title="Change description." />
        </f:facet>
        <p:commandLink update=":#{popupName}Form"
          oncomplete="PF('#{popupName}').show('#{component.clientId}');"
          styleClass="ellipsis">
          <f:setPropertyActionListener value="Change"
            target="#{historyRequestManager.longTextOverlayHeader}" />
          <f:setPropertyActionListener value="#{history.entry}"
            target="#{historyRequestManager.longTextOverlayContent}" />
          <h:outputText value="#{history.entry}" />
        </p:commandLink>
      </p:column>

    </p:dataTable>
  </div>
</ui:composition>