cabledb/src/main/java/org/openepics/cable/model/Artifact.java
/*
 * Copyright (c) 2014 European Spallation Source
 * Copyright (c) 2014 Cosylab d.d.
 *
 * This file is part of Controls Configuration Database.
 *
 * Controls Configuration Database is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of the License,
 * or any newer version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see https://www.gnu.org/licenses/gpl-2.0.txt
 */
package org.openepics.cable.model;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.Date;

import javax.faces.context.FacesContext;
import javax.persistence.Entity;
import javax.persistence.Transient;

import org.apache.commons.io.FilenameUtils;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultStreamedContent;

import com.google.common.io.ByteStreams;

/**
 * An artifact is a user-defined value that is attached to database entities such as a file
 *
 * @author <a href="mailto:sunil.sah@cosylab.com">Sunil Sah</a>
 */
@Entity
public class Artifact extends Persistable {

    private static final long serialVersionUID = 2926588619140123269L;

    private String name;
    private String description;
    private String uri;
    private String rooturi;
    protected Date modifiedAt = new Date(0L);
    protected String modifiedBy;

    @Transient
    private String newName;
    @Transient
    private byte[] importData;

    /** Constructor. */
    public Artifact() {}

    /**
     * Constructs a new artifact
     * 
     * @param name
     *            the name of the artifact
     * @param description
     *            the user specified description
     * @param uri
     *            the user specified URL
     * @param rootUri
     *            the uri to the storage folder
     */
    public Artifact(String name, String description, String uri, String rootUri) {
        this.name = name;
        this.description = description;
        this.uri = uri;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    public String getRootUri() {
        return rooturi != null ? rooturi : File.separator;
    }

    public void setRootUri(String rootUri) {
        this.rooturi = rootUri;
    }

    /** @return The timestamp of the last modification of this database entity */
    public Date getModifiedAt() {
        return new Date(modifiedAt.getTime());
    }

    /**
     * The setter stores a new copy of the param.
     *
     * @param modifiedAt
     *            The timestamp of the last modification of this database entity
     */
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = new Date(modifiedAt.getTime());
    }

    /** @return The user performing the last modification of the database entity */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * @param modifiedBy
     *            The user performing the last modification of the database entity
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }

    @Override
    public boolean equals(Object object) {
        if ((object == null) || (object.getClass() != this.getClass())) {
            return false;
        }

        Artifact other = (Artifact) object;
        if (this.id == null && other.id != null) {
            return false;
        }

        // return true for the same DB entity
        if (this.id != null) {
            return this.id.equals(other.id);
        }

        return this == object;
    }

    /** @return newName the name that will be set to artifact after save */
    public String getNewName() {
        return newName != null ? newName : getName();
    }

    /** Sets artifact name to name of uploaded file. */
    public void updateName() {
        setName(newName);
    }

    public byte[] getImportData() {
        return importData;
    }

    /**
     * Finds artifact file that was uploaded on the file system and returns it to be downloaded
     * 
     * @return Artifact file to be downloaded
     * @throws FileNotFoundException
     *             Thrown if file was not found on file system
     */
    public DefaultStreamedContent getDownloadFile() throws FileNotFoundException {
        // guess mime type based on the original file name, not on the name of the blob (UUID).
        final String contentType = FacesContext.getCurrentInstance().getExternalContext().getMimeType(getName());
        return new DefaultStreamedContent(new FileInputStream(getRootUri() + getUri()), contentType, getName());
    }

    /**
     * Uploads file to be saved in the Artifact
     * 
     * @param event
     *            the {@link FileUploadEvent}
     */
    public void handleImportFileUpload(FileUploadEvent event) {
        try (InputStream inputStream = event.getFile().getInputstream()) {
            this.importData = ByteStreams.toByteArray(inputStream);
            this.newName = FilenameUtils.getName(event.getFile().getFileName());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

}

cabledb/src/main/java/org/openepics/cable/model/Cable.java
/*
 * Copyright (c) 2014 European Spallation Source
 * Copyright (c) 2014 Cosylab d.d.
 *
 * This file is part of Cable Database.
 * Cable Database is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 2 of the License, or any newer version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see https://www.gnu.org/licenses/gpl-2.0.txt
 */
package org.openepics.cable.model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.OrderColumn;

import com.google.common.base.Preconditions;

/**
 * This represents an instance of cable.
 *
 * @author <a href="mailto:sunil.sah@cosylab.com">Sunil Sah</a>
 */
@Entity
public class Cable extends Persistable {

    private static final long serialVersionUID = -7654156206144341815L;

    /** This represents the data validity of the cable. */
    public enum Validity {
        /** The cable state approved, this is the default status. */
        VALID,
        /** One of the cable endpoints is not in valid state. */
        DANGLING
    }

    private String system;
    private String subsystem;
    private String cableClass;
    private Integer seqNumber;
    @ElementCollection(fetch = FetchType.LAZY)
    @OrderColumn(name = "position")
    private List<String> owners = new ArrayList<>();
    private String ownersString;

    @ManyToOne
    private CableType cableType;
    private String container;
    @OneToOne
    private Endpoint endpointA;
    @OneToOne
    private Endpoint endpointB;

    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY, mappedBy = "cable")
    @OrderColumn(name = "position")
    private List<RoutingRow> routingRows = new ArrayList<>();
    private String routingsString;

    private Date installationBy;
    private Date terminationBy;
    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private Artifact qualityReport;
    @Enumerated(EnumType.STRING)
    private CableAutoCalculatedLength autoCalculatedLength = CableAutoCalculatedLength.NO;
    private Float baseLength;
    private Float length;
    private Date created;
    private Date modified;
    @Enumerated(EnumType.STRING)
    private CableStatus status = CableStatus.INSERTED;
    @Enumerated(EnumType.STRING)
    private Validity validity = Validity.VALID;

    /** Constructor for JPA entity. */
    private Cable() {}

    /**
     * Creates a new instance of a cable.
     *
     * @param system
     *            the cable system digit
     * @param subsystem
     *            the cable subsystem digit
     * @param cableClass
     *            the cable class letter
     * @param seqNumber
     *            the cable sequential number
     * @param owners
     *            the cable owners
     * @param created
     *            the creation date of this cable
     * @param modified
     *            the modification date of this cable
     */
    public Cable(String system, String subsystem, String cableClass, Integer seqNumber, List<String> owners,
            Date created, Date modified) {
        this(system, subsystem, cableClass, seqNumber, owners, CableStatus.INSERTED, null, null, null, null, created,
                modified, null, null, null, null, CableAutoCalculatedLength.NO, null);
    }

    /**
     * Creates a new instance of a cable.
     *
     * @param system
     *            the cable system digit
     * @param subsystem
     *            the cable subsystem digit
     * @param cableClass
     *            the cable class letter
     * @param seqNumber
     *            the cable sequential number
     * @param owners
     *            the cable owners
     * @param status
     *            the cable status
     * @param cableType
     *            the cable type
     * @param container
     *            the container cable number of this cable
     * @param endpointA
     *            endpoint a of the cable
     * @param endpointB
     *            endpoint b of the cable
     * @param created
     *            the creation date of this cable
     * @param modified
     *            the modification date of this cable
     * @param routingRows
     *            the routing value for this cable instance
     * @param installationBy
     *            the date by which this cable is installed
     * @param terminationBy
     *            the date by which this cable is terminated
     * @param qualityReport
     *            the qualityReport artifact
     * @param autoCalculatedLength
     *            boolean indicating if length was auto calculated
     * @param length
     *            the user specified cable length
     */
    public Cable(String system, String subsystem, String cableClass, Integer seqNumber, List<String> owners,
            CableStatus status, CableType cableType, String container, Endpoint endpointA, Endpoint endpointB,
            Date created, Date modified, List<RoutingRow> routingRows, Date installationBy, Date terminationBy,
            Artifact qualityReport, CableAutoCalculatedLength autoCalculatedLength, Float length) {
        Preconditions.checkArgument(owners != null && !owners.isEmpty());
        Preconditions.checkNotNull(status);
        Preconditions.checkNotNull(created);
        Preconditions.checkNotNull(modified);

        final CableName cableName = new CableName(system, subsystem, cableClass, seqNumber != null ? seqNumber : 0);
        this.system = cableName.getSystem();
        this.subsystem = cableName.getSubsystem();
        this.cableClass = cableName.getCableClass();
        this.seqNumber = seqNumber != null ? cableName.getSeqNumber() : null;

        this.owners.addAll(owners);
        updateOwnersString();
        this.status = status;
        this.cableType = cableType;
        this.container = container;
        this.endpointA = endpointA;
        this.endpointB = endpointB;
        this.created = created; // NOSONAR
        this.modified = modified; // NOSONAR

        setRoutingRows(routingRows);

        this.installationBy = installationBy; // NOSONAR
        this.terminationBy = terminationBy; // NOSONAR
        this.qualityReport = qualityReport != null ? qualityReport : new Artifact();
        this.autoCalculatedLength = autoCalculatedLength;
        this.baseLength = 0f;
        this.length = length;
    }

    /**
     * Updates routings.
     */
    public void updateRoutings() {
        if (routingRows != null) {
            Collections.sort(routingRows, (a, b) -> a.getPosition() - b.getPosition());// Sort by position
            List<String> routingNames = new ArrayList<String>();
            for (RoutingRow routing : routingRows) {
                if (routing.getRouting().isActive()) {
                    routingNames.add(routing.getRouting().getName());
                } else {
                    routingNames.add("<strike>" + routing.getRouting().getName() + "</strike>");
                }
            }
            this.routingsString = String.join(", ", routingNames);
        } else {
            this.routingsString = "";
        }
    }

    /**
     * Sets the modified date of this cable instance.
     *
     * @param modified
     *            the modified date to set
     */
    public void setModified(Date modified) {
        this.modified = modified; // NOSONAR
    }

    /**
     * Sets the status of this cable instance.
     *
     * @param status
     *            the status to set
     */
    public void setStatus(CableStatus status) {
        Preconditions.checkNotNull(status);
        this.status = status;
    }

    /**
     * Sets the validity of this cable instance.
     *
     * @param validity
     *            the validity to set
     */
    public void setValidity(Validity validity) {
        this.validity = validity;
    }

    /** @return the cable number (example: 12A012345) */
    public String getName() {
        return CableName.asString(system, subsystem, cableClass, seqNumber);
    }

    /** @return the cable system digit */
    public String getSystem() {
        return system;
    }

    /** @return the cable subsystem digit */
    public String getSubsystem() {
        return subsystem;
    }

    /** @return the cable class letter */
    public String getCableClass() {
        return cableClass;
    }

    /** @return the cable sequential number */
    public Integer getSeqNumber() {
        return seqNumber;
    }

    /** @return the cable owners */
    public List<String> getOwners() {
        return owners;
    }

    /** Updates owners string. */
    public void updateOwnersString() {
        ownersString = String.join(", ", owners);
    }

    /** @return the cable owners joined in a string */
    public String getOwnersString() {
        return ownersString;
    }

    /** @return the routing value for this cable instance */
    public List<RoutingRow> getRoutingRows() {
        return routingRows;
    }

    /** @return the date by which this cable is installed */
    public Date getInstallationBy() {
        return installationBy; // NOSONAR
    }

    /** @return the date by which this cable is terminated */
    public Date getTerminationBy() {
        return terminationBy; // NOSONAR
    }

cabledb/src/main/java/org/openepics/cable/model/DeviceStatus.java
/*
 * Copyright (c) 2014 European Spallation Source
 * Copyright (c) 2014 Cosylab d.d.
 *
 * This file is part of Cable Database.
 * Cable Database is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 2 of the License, or any newer version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see https://www.gnu.org/licenses/gpl-2.0.txt
 */
package org.openepics.cable.model;

/**
 * This represents the device status retrieved from naming service.
 *
 * @author <a href="mailto:sunil.sah@cosylab.com">Sunil Sah</a>
 */
public enum DeviceStatus {
    NONE,
    ACTIVE,
    DELETED,
    OBSOLETE;
}

cabledb/src/main/webapp/resources/dialogs/cable-extremities.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:p="http://primefaces.org/ui"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:h="http://java.sun.com/jsf/html">
  <h:form id="cableExtremitiesForm">
    <p:dialog widgetVar="cableExtremitiesDialog"
      id="cableExtremitiesDialog" modal="true" resizable="false"
      closable="false" width="400" dynamic="true">
      <f:facet name="header">
        <h:outputText
          value="Show #{cableRequestManager.selectedDevice} in..." />
      </f:facet>
      <p:panelGrid id="grp" styleClass="borderless" columns="1"
        style="margin-bottom: 1ex;">
        <h:commandLink target="_blank"
          actionListener="#{cableRequestManager.redirectToNamingService}">
          <h:outputText value="Naming Service"
            style="color: blue; text-decoration: underline;" />
        </h:commandLink>
        <h:commandLink target="_blank"
          actionListener="#{cableRequestManager.redirectToCCDB}">
          <h:outputText value="Controls Configuration DB"
            style="color: blue; text-decoration: underline;" />
        </h:commandLink>
      </p:panelGrid>
      <p:commandButton ajax="true" value="Close" title="Close dialog."
        styleClass="dialogButton"
        onclick="PF('cableExtremitiesDialog').hide();" update="grp" />
    </p:dialog>
  </h:form>
</ui:composition>

cabledb/src/main/webapp/resources/dialogs/cable-type.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:p="http://primefaces.org/ui"
  xmlns:o="http://omnifaces.org/ui"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:h="http://java.sun.com/jsf/html">

  <h:form id="#{formId}">
    <p:dialog widgetVar="#{widgetName}" id="#{widgetName}" modal="true"
      resizable="false" closable="false" width="800" dynamic="true">
      <f:facet name="header">
        <h:outputText value="#{dialogTitle}" />
      </f:facet>
      <p:panelGrid id="grp" styleClass="borderless" columns="2"
        style="margin-bottom: 1ex; width:100%"
        columnClasses="one-third top-alignment, two-thirds top-alignment">

        <p:outputLabel for="cableTypeName" value="Name:" />
        <h:panelGroup>
          <p:inputText id="cableTypeName"
            value="#{cableTypeRequestManager.selectedCableType.name}"
            readonly="#{!cableTypeRequestManager.addPopupOpened}"
            required="true" requiredMessage="Name is required."
            validator="#{cableTypeRequestManager.isCableTypeNameValid}"
            style="width:100%" />
          <p:message for="cableTypeName" />
        </h:panelGroup>

        <p:outputLabel for="cableTypeDescription" value="Description:"
          style="margin-top: 0px" />
        <p:inputTextarea id="cableTypeDescription" autoResize="false"
          scrollHeight="5" rows="5" maxlength="65535"
          style="width:100%; resize: none;"
          value="#{cableTypeRequestManager.selectedCableType.description}" />

        <p:outputLabel for="cableTypeService" value="Service/Function:" />
        <p:inputText id="cableTypeService"
          value="#{cableTypeRequestManager.selectedCableType.service}"
          maxlength="255" style="width:100%" />

        <p:outputLabel for="cableTypeDiameter" value="Diameter (mm):" />
        <h:panelGroup>
          <p:inputText id="cableTypeDiameter"
            value="#{cableTypeRequestManager.selectedCableType.diameter}"
            validator="#{cableTypeRequestManager.isFloatEntered}"
            maxlength="255" style="width:100%" />
          <p:message for="cableTypeDiameter" />
        </h:panelGroup>

        <p:outputLabel for="cableTypeWeight" value="Weight (kg/m):" />
        <h:panelGroup>
          <p:inputText id="cableTypeWeight"
            value="#{cableTypeRequestManager.selectedCableType.weight}"
            validator="#{cableTypeRequestManager.isFloatEntered}"
            maxlength="255" style="width:100%" />
          <p:message for="cableTypeWeight" />
        </h:panelGroup>

        <p:outputLabel for="cableTypeInsulation" value="Insulation:" />
        <p:inputText id="cableTypeInsulation"
          value="#{cableTypeRequestManager.selectedCableType.insulation}"
          maxlength="255" style="width:100%" />

        <p:outputLabel for="cableTypeJacket" value="Jacket:" />
        <p:inputText id="cableTypeJacket"
          value="#{cableTypeRequestManager.selectedCableType.jacket}"
          maxlength="255" style="width:100%" />

        <p:outputLabel for="cableTypeVoltage"
          value="Voltage Rating (V):" />
        <h:panelGroup>
          <p:inputText id="cableTypeVoltage"
            value="#{cableTypeRequestManager.selectedCableType.voltage}"
            validator="#{cableTypeRequestManager.isIntegerEntered}"
            maxlength="255" style="width:100%" />
          <p:message for="cableTypeVoltage" />
        </h:panelGroup>

        <p:outputLabel for="cableTypeFlammab" value="Flammable Class:" />
        <p:inputText id="cableTypeFlammab"
          value="#{cableTypeRequestManager.selectedCableType.flammability}"
          maxlength="255" style="width:100%" />

        <p:outputLabel for="cableTypeInstallationType"
          value="Installation Type:" />
        <p:selectOneMenu id="cableTypeInstallationType"
          value="#{cableTypeRequestManager.selectedCableType.installationTypeString}"
          style="width: calc(100% - 28px)">
          <f:selectItems
            value="#{cableTypeRequestManager.installationTypesWithoutAll}"
            var="installationType" itemLabel="#{installationType.label}"
            itemValue="#{installationType.value}" />
        </p:selectOneMenu>

        <p:outputLabel for="cableTypeTID"
          value="Radiation Resistance (mrad):" />
        <h:panelGroup>
          <p:inputText id="cableTypeTID"
            value="#{cableTypeRequestManager.selectedCableType.tid}"
            validator="#{cableTypeRequestManager.isFloatEntered}"
            maxlength="255" style="width:100%" />
          <p:message for="cableTypeTID" />
        </h:panelGroup>

        <p:outputLabel for="#{widgetName}cableTypeManufacturerTable"
          value="Manufacturers:" />
        <p:fieldset id="cableTypeManufacturers">
          <p:dataTable id="#{widgetName}cableTypeManufacturerTable"
            var="cableTypeManufacturer"
            value="#{cableTypeRequestManager.selectedCableType.manufacturers}"
            rowKey="#{cableTypeManufacturer.position}"
            widgetVar="#{widgetName}cableTypeManufacturerTable"
            scrollable="true" scrollHeight="100" scrollRows="5"
            editable="true" editMode="cell"
            sortBy="#{cr.position}" sortOrder="ascending"
            emptyMessage="No records found."
            selection="#{cableTypeRequestManager.selectedCableTypeManufacturer}"
            selectionMode="single">

            <p:ajax event="rowSelect" process="@this"
              update=":#{formId}:buttons" />
            <p:ajax event="rowUnselect" process="@this"
              update=":#{formId}:buttons" />
            <p:column>
              <f:facet name="header">
                <h:outputText value="Manufacturer"
                  title="Manufacturer of the cable type." />
              </f:facet>
              <p:cellEditor>
                <f:facet name="output">
                  <h:outputText
                    value="#{cableTypeManufacturer.manufacturer.name}" />
                </f:facet>
                <f:facet name="input">
                  <p:autoComplete
                    value="#{cableTypeManufacturer.manufacturer}"
                    completeMethod="#{cableTypeRequestManager.completeAvailableManufacturers}"
                    var="manufacturer" itemLabel="#{manufacturer.name}" itemValue="#{manufacturer}"
                    style="width:100%" dropdown="true"
                    forceSelection="true" maxResults="10">
                     <o:converter converterId="omnifaces.ListConverter" list="#{cableTypeRequestManager.availableManufacturers}" />
                  </p:autoComplete>
                </f:facet>
              </p:cellEditor>
            </p:column>
            <p:column>
              <f:facet name="header">
                <h:outputText value="Datasheet"
                  title="Datasheet of the manufacturer." />
              </f:facet>
              <h:outputText
                value="#{cableTypeManufacturer.datasheet.newName}" />
            </p:column>
          </p:dataTable>
          <p:panel id="buttons" styleClass="buttonRowCondensed">
            <p:commandButton value="Add" title="Add manufacturer."
              icon="ui-icon-plus"
              disabled="#{!cableTypeRequestManager.changeCableTypeManufacturersPermission}"
              action="#{cableTypeRequestManager.addCableTypeManufacturer}"
              update=":#{formId}:#{widgetName}cableTypeManufacturerTable"
              process="@this" />
            <p:commandButton value="Delete"
              title="Delete selected manufacturer."
              icon="ui-icon-trash"
              disabled="#{cableTypeRequestManager.selectedCableTypeManufacturer == null or !cableTypeRequestManager.changeCableTypeManufacturersPermission}"
              action="#{cableTypeRequestManager.removeCableTypeManufacturer}"
              update=":#{formId}:cableTypeManufacturers" process="@this" />
            <p:commandButton id="moveUp" value="Up"
              title="Move selected manufacturer up."
              icon="ui-icon-arrowthick-1-n"
              disabled="#{cableTypeRequestManager.selectedCableTypeManufacturer == null}"
              update=":#{formId}:buttons :#{formId}:#{widgetName}cableTypeManufacturerTable"
              action="#{cableTypeRequestManager.moveManufacturerUp()}"
              process="@this" />
            <p:commandButton id="moveDown" value="Down"
              title="Move selected manufacturer down."
              icon="ui-icon-arrowthick-1-s"
              disabled="#{cableTypeRequestManager.selectedCableTypeManufacturer == null}"
              update=":#{formId}:buttons :#{formId}:#{widgetName}cableTypeManufacturerTable"
              process="@this"
              action="#{cableTypeRequestManager.moveManufacturerDown()}" />
            <p:fileUpload label="Add Datasheet"
              fileUploadListener="#{cableTypeRequestManager.selectedCableTypeManufacturer.datasheet.handleImportFileUpload}"
              disabled="#{cableTypeRequestManager.selectedCableTypeManufacturer == null or !cableTypeRequestManager.changeCableTypeManufacturersPermission}"
              modelistener="advanced"
              update=":#{formId}:#{widgetName}cableTypeManufacturerTable"
              auto="true" fileLimit="1" dragDropSupport="false"
              process="@this" styleClass="uploadButton" />
          </p:panel>
        </p:fieldset>

        <p:outputLabel for="cableTypeComments" value="Comments:" />
        <p:inputTextarea id="cableTypeComments" autoResize="false"
          scrollHeight="5" rows="5" maxlength="255"
          style="width:100%; resize: none;"
          value="#{cableTypeRequestManager.selectedCableType.comments}" />

      </p:panelGrid>

      <p:panel styleClass="buttonRowCondensed">
        <p:commandButton value="Save" title="Save cable type."
          styleClass="dialogButton" onstart="start()"
          oncomplete="stop(); if (args &amp;&amp; !args.validationFailed) { PF('#{widgetName}').hide(); updateCableTypeTable();}"
          action="#{cableTypeRequestManager[submitHandler]}"
          update=":cableTypeTableForm grp" icon="ui-icon-disk" />
        <p:commandButton value="Cancel" title="Cancel all changes."
          styleClass="dialogButton" onclick="PF('#{widgetName}').hide();"
          actionListener="#{cableTypeRequestManager.clearSelection()}"
          update="grp :cableTypeTableForm:buttons" resetValues="true"
          icon="ui-icon-close" process="@this" />
      </p:panel>
    </p:dialog>
  </h:form>
</ui:composition>

cabledb/src/main/webapp/resources/dialogs/display-long-manufacturers.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:p="http://primefaces.org/ui"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:h="http://java.sun.com/jsf/html">
  <h:form id="displayLongManufacturersForm">
    <p:overlayPanel id="displayLongManufacturersPanel"
      widgetVar="displayLongManufacturersPanel" dismissable="false"
      showCloseIcon="true" style="max-width: 512px; max-height:512px;" styleClass="ovelrayWithLinks">
      <p:outputPanel>
        <p:panel styleClass="overlayPanel">
          <f:facet name="header">
            <h:outputText value="Cable Type Manufacturers" />
          </f:facet>
        </p:panel>
        <p:panel id="displayLongManufacturersContentPanel"
          style="overflow: auto">
          <ui:repeat value="#{cableType.manufacturers}" var="m"
            varStatus="status">
            <h:outputLink
              value="#{cableType.getManufacturerUrl(m.manufacturer)}"
              styleClass="#{m.manufacturer.status != ManufacturerStatus.DELETED ? '' : 'entity-deleted'}">
              <h:outputText value="#{m.manufacturer.name}" />
            </h:outputLink>
            #{m.datasheet.name != null ? " (" : ""}<p:commandLink ajax="false" title="Download"
              style="margin:0;"
              rendered="#{m.datasheet.name != null}"
              styleClass="#{m.manufacturer.status != ManufacturerStatus.DELETED ? '' : 'entity-deleted'}">
              <h:outputText value="#{m.datasheet.name}" />
              <p:fileDownload value="#{m.datasheet.downloadFile}" />
            </p:commandLink>#{m.datasheet.name != null ? ")" : ""}#{status.last ? '' : ','}
          </ui:repeat>
        </p:panel>
      </p:outputPanel>
    </p:overlayPanel>
  </h:form>

</ui:composition>